// The same words in English, key for key and in the same order.

export const en = {
	'about.author': 'Author',
	'about.contact': 'Contact',
	'about.date': 'Date',
	'about.dirty': 'local changes',
	'about.heading.stack': 'Technology',
	'about.heading.what': 'What it actually does',
	'about.heading.why': 'What sets it apart',
	'about.revision': 'Revision',
	'about.version': 'Version',
	'about.year': 'Year',
	'common.cancel': 'Cancel',
	'common.close': 'Close',
	'common.confirm': 'Confirm',
	'common.failed': 'The request failed ({status}).',
	'common.ok': 'OK',
	'common.requestFailed': 'Error: {detail}',
	'common.save': 'Save',
	'common.saving': 'Saving…',
	'common.timeout': 'The server is not answering.',
	'common.unreachable': 'The server cannot be reached.',
	'frame.account': 'Account',
	'frame.logout': 'Sign out',
	'frame.more': 'More',
	'frame.signedInAs': 'Signed in as',
	'help.group.concepts': 'Concepts',
	'help.group.operating': 'Operating',
	'help.more': 'Learn more',
	'help.notFound': 'Article not found.',
	'help.title': 'Help',
	'letters.label': 'Letters',
	'runtime.hours': '{h} h',
	'runtime.minutes': '{m} min',
	'settings.bool.off': 'Off',
	'settings.bool.on': 'On',
	'settings.err.bad_value': 'value not allowed',
	'settings.err.not_a_number': 'value is not a number',
	'settings.err.not_editable': 'this setting cannot be changed',
	'settings.err.unknown_key': 'unknown setting',
	'settings.saveFailed': 'Settings not saved — {field}: {reason}',
	'settings.saved': 'Settings saved.',
	'settings.secretSet': '•••••••• (set — leave blank to keep)',
	'settings.secretUnset': 'not set',
	'settings.unsaved': 'Unsaved changes',
	'version.available': 'Version {version} is available.',
	'version.installed': 'Updated to version {version}.',
	'version.reload': 'Reload',
} as const;
