// The same words in English, key for key and in the same order.

export const en = {
	'common.cancel': 'Cancel',
	'common.close': 'Close',
	'common.confirm': 'Confirm',
	'common.ok': 'OK',
	'common.requestFailed': 'Error: {detail}',
	'common.save': 'Save',
	'common.saving': 'Saving…',
	'common.unreachable': 'The server is not answering.',
	'letters.label': 'Letters',
	'runtime.hours': '{h} h',
	'runtime.minutes': '{m} min',
	'settings.bool.off': 'Off',
	'settings.bool.on': 'On',
	'settings.err.bad_value': 'value not allowed',
	'settings.err.not_a_number': 'value is not a number',
	'settings.err.not_editable': 'this setting cannot be changed',
	'settings.err.unknown_key': 'unknown setting',
	'settings.saveFailed': 'Settings not saved — {field}: {reason}',
	'settings.saved': 'Settings saved.',
	'settings.secretSet': '•••••••• (set — leave blank to keep)',
	'settings.secretUnset': 'not set',
	'settings.unsaved': 'Unsaved changes',
	'version.available': 'Version {version} is available.',
	'version.installed': 'Updated to version {version}.',
	'version.reload': 'Reload',
} as const;
