// The same words in English. Croatian is the source of truth: a key is written
// there first, then here.

export const en = {
	'account.changed': 'The password was changed.',
	'account.current': 'Current password',
	'account.err.blank': 'Fill in both passwords.',
	'account.err.mismatch': 'The new passwords do not match.',
	'account.err.rejected': 'The current password is not right.',
	'account.new': 'New password',
	'account.password': 'Password',
	'account.repeat': 'Repeat the new password',
	'account.token': 'Service token',
	'account.tokenShow': 'Show',
	'account.yours': 'Your account',
	'common.save': 'Save',
	'common.saving': 'Saving…',
	'lang.switch': 'Prebaci na hrvatski',
	'login.failed': 'Wrong username or password.',
	'login.missing': 'Enter a username and a password.',
	'login.password': 'Password',
	'login.submit': 'Sign in',
	'login.username': 'Username',
	'login.working': 'Signing in…',
	'people.add': 'Add a person',
	'people.disable': 'Disable',
	'people.disabled': 'disabled',
	'people.display': 'Full name',
	'people.dropOwner': 'Remove ownership',
	'people.enable': 'Enable',
	'people.err.blank': 'A person needs a username and a password.',
	'people.err.failed': 'That change did not go through.',
	'people.err.mismatch': 'The passwords do not match.',
	'people.err.notOwner': 'Only an owner may change the roster.',
	'people.err.refused': 'An install needs at least one owner, and you cannot remove yourself.',
	'people.err.short': 'A password needs at least 8 characters — the vault key is derived from it.',
	'people.makeOwner': 'Make an owner',
	'people.name': 'Username',
	'people.newPassword': 'New password',
	'people.owner': 'owner',
	'people.password': 'Password',
	'people.remove': 'Remove',
	'people.repeat': 'Repeat the password',
	'people.reset': 'Set password',
	'people.title': 'People',
	'people.wasAdded': '{name} has been added.',
	'people.you': 'you',
	'photos.close': 'Close',
	'photos.count': '{n} photos',
	'photos.empty': 'No photos here yet.',
	'photos.jump': 'Jump to a period',
	'photos.loading': 'Loading…',
	'photos.next': 'Next',
	'photos.notThisPerson': 'Not this person — takes the name off this face',
	'photos.placeSpread': 'written on {n} photos',
	'photos.prev': 'Previous',
	'photos.thisOne': 'just this one',
	'photos.undated.n': '{n} without a date',
	'photos.unknownFace': 'An unnamed face',
	'photos.unknownFaces': '{n} more faces',
	'photos.unnamedPlace': '+ name this place',
	'photos.unreadable': 'This photo cannot be shown',
	'photos.whereAsk': 'Where was this taken?',
	'photos.whereUnknown': '+ place',
	'photos.wholeDay': 'the whole day',
	'prefs.language': 'Language',
	'prefs.theme': 'Theme',
	'settings.bool.off': 'Off',
	'settings.bool.on': 'On',
	'settings.secretSet': '•••••••• (set — leave blank to keep)',
	'settings.secretUnset': 'not set',
	'theme.dark': 'Dark theme',
	'theme.light': 'Light theme',
	'theme.pick.dark': 'Dark',
	'theme.pick.light': 'Light',
	'theme.pick.system': 'System',
	'theme.system': 'System theme',
} as const;
