// The words the kit itself says, in Croatian, which is where a word is
// written first. A module says only what it alone knows; saying one of these
// again throws at boot.

export const hr = {
	'about.author': 'Autor',
	'about.contact': 'Kontakt',
	'about.date': 'Datum',
	'about.dirty': 'lokalne izmjene',
	'about.heading.stack': 'Tehnologija',
	'about.heading.what': 'Što stvarno radi',
	'about.heading.why': 'Po čemu se razlikuje',
	'about.revision': 'Revizija',
	'about.version': 'Verzija',
	'about.year': 'Godina',
	'common.cancel': 'Odustani',
	'common.close': 'Zatvori',
	'common.confirm': 'Potvrdi',
	'common.ok': 'U redu',
	'common.requestFailed': 'Greška: {detail}',
	'common.save': 'Spremi',
	'common.saving': 'Spremam…',
	'common.unreachable': 'Poslužitelj ne odgovara.',
	'frame.account': 'Račun',
	'frame.logout': 'Odjava',
	'frame.more': 'Više',
	'frame.signedInAs': 'Prijavljeni ste kao',
	'letters.label': 'Slova',
	'runtime.hours': '{h} h',
	'runtime.minutes': '{m} min',
	'settings.bool.off': 'Isključeno',
	'settings.bool.on': 'Uključeno',
	'settings.err.bad_value': 'nedozvoljena vrijednost',
	'settings.err.not_a_number': 'vrijednost nije broj',
	'settings.err.not_editable': 'postavka se ne može mijenjati',
	'settings.err.unknown_key': 'nepoznata postavka',
	'settings.saveFailed': 'Postavke nisu spremljene — {field}: {reason}',
	'settings.saved': 'Postavke su spremljene.',
	'settings.secretSet': '•••••••• (postavljeno — ostavite prazno za nepromijenjeno)',
	'settings.secretUnset': 'nije postavljeno',
	'settings.unsaved': 'Nespremljene promjene',
	'version.available': 'Dostupna je nova verzija {version}.',
	'version.installed': 'Aplikacija je ažurirana na verziju {version}.',
	'version.reload': 'Osvježi',
} as const;
