// The words the package itself says, in Croatian, which is where a word is
// written first.
//
// These belong here because the components that render them are here. They used
// to be a list the package OBLIGED every module to carry — and three modules
// each satisfying that contract on their own is how the same login form came to
// ask for a Zaporka in two of them and a Lozinka in the third. A module says
// what only it knows: its own domain, its own fields, its own engines.

export const hr = {
	'account.changed': 'Zaporka je promijenjena.',
	'account.current': 'Trenutna zaporka',
	'account.err.blank': 'Ispunite obje zaporke.',
	'account.err.mismatch': 'Nove zaporke se ne podudaraju.',
	'account.err.rejected': 'Trenutna zaporka nije točna.',
	'account.new': 'Nova zaporka',
	'account.password': 'Zaporka',
	'account.repeat': 'Ponovite novu zaporku',
	'account.token': 'Servisni token',
	'account.tokenShow': 'Prikaži',
	'account.yours': 'Vaš račun',
	'common.save': 'Spremi',
	'common.saving': 'Spremam…',
	'lang.switch': 'Switch to English',
	'login.failed': 'Neispravno korisničko ime ili zaporka.',
	'login.missing': 'Upišite korisničko ime i zaporku.',
	'login.password': 'Zaporka',
	'login.submit': 'Prijava',
	'login.username': 'Korisničko ime',
	'login.working': 'Prijavljujem…',
	'people.add': 'Dodaj osobu',
	'people.disable': 'Onemogući',
	'people.disabled': 'onemogućen',
	'people.display': 'Ime i prezime',
	'people.dropOwner': 'Ukloni vlasništvo',
	'people.enable': 'Omogući',
	'people.err.blank': 'Osoba treba korisničko ime i zaporku.',
	'people.err.failed': 'Promjena nije provedena.',
	'people.err.mismatch': 'Zaporke se ne podudaraju.',
	'people.err.notOwner': 'Popis osoba može mijenjati samo vlasnik.',
	'people.err.refused': 'Instalacija mora imati barem jednog vlasnika, a sebe ne možete ukloniti.',
	'people.err.short': 'Zaporka mora imati barem 8 znakova — iz nje se izvodi ključ trezora.',
	'people.makeOwner': 'Postavi za vlasnika',
	'people.name': 'Korisničko ime',
	'people.newPassword': 'Nova zaporka',
	'people.owner': 'vlasnik',
	'people.password': 'Zaporka',
	'people.remove': 'Ukloni',
	'people.repeat': 'Ponovite zaporku',
	'people.reset': 'Postavi zaporku',
	'people.title': 'Ljudi',
	'people.wasAdded': 'Osoba {name} je dodana.',
	'people.you': 'vi',
	'photos.close': 'Zatvori',
	'photos.count': '{n} fotografija',
	'photos.empty': 'Ovdje još nema fotografija.',
	'photos.jump': 'Skoči na razdoblje',
	'photos.loading': 'Učitavam…',
	'photos.next': 'Sljedeća',
	'photos.notThisPerson': 'Nije ova osoba — skida ime s ovog lica',
	'photos.placeSpread': 'upisano na {n} fotografija',
	'photos.prev': 'Prethodna',
	'photos.thisOne': 'samo ova',
	'photos.undated.n': '{n} bez datuma',
	'photos.unknownFace': 'Neimenovano lice',
	'photos.unknownFaces': 'još lica: {n}',
	'photos.unnamedPlace': '+ ime mjesta',
	'photos.unreadable': 'Ovu fotografiju nije moguće prikazati',
	'photos.whereAsk': 'Gdje je snimljeno?',
	'photos.whereUnknown': '+ mjesto',
	'photos.wholeDay': 'cijeli dan',
	'prefs.language': 'Jezik',
	'prefs.theme': 'Tema',
	'settings.bool.off': 'Isključeno',
	'settings.bool.on': 'Uključeno',
	'settings.secretSet': '•••••••• (postavljeno — ostavite prazno za nepromijenjeno)',
	'settings.secretUnset': 'nije postavljeno',
	'theme.dark': 'Tamna tema',
	'theme.light': 'Svijetla tema',
	'theme.pick.dark': 'Tamna',
	'theme.pick.light': 'Svijetla',
	'theme.pick.system': 'Prema sustavu',
	'theme.system': 'Tema prema sustavu',
} as const;
